#!/bin/bash

# Supabaseプロジェクトの情報
PROJECT_REF="rbdncduyukqufnpcqckd"
SQL_EDITOR_URL="https://supabase.com/dashboard/project/${PROJECT_REF}/editor"
REPLICATION_URL="https://supabase.com/dashboard/project/${PROJECT_REF}/database/replication"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎮 Supabase セットアップガイド"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 以下の手順でSupabaseのスキーマを適用してください:"
echo ""
echo "【ステップ1】SQL Editorでスキーマを作成"
echo ""
echo "1. 以下のURLをブラウザで開く:"
echo "   ${SQL_EDITOR_URL}"
echo ""
echo "2. 「New query」ボタンをクリック"
echo ""
echo "3. 以下のファイルの内容をコピー＆ペースト:"
echo "   📄 supabase/schema.sql"
echo ""
echo "4. 「Run」ボタン（または Cmd/Ctrl + Enter）で実行"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "【ステップ2】Realtimeを有効化"
echo ""
echo "1. 以下のURLをブラウザで開く:"
echo "   ${REPLICATION_URL}"
echo ""
echo "2. テーブル一覧から「game_sessions」を探す"
echo ""
echo "3. 右側の「Enable」ボタンをクリック"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 完了したら、アプリが正常に動作するようになります！"
echo ""
echo "💡 確認方法:"
echo "   - npm run dev でローカルサーバーを起動"
echo "   - ゲームを作成して動作確認"
echo ""
